# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Smart care bedside display system' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Smart Healthcare App
    pod 'lottie-ios' , '4.2.0'
    pod 'CCAutocomplete' , '0.0.6'
    pod 'IQKeyboardManager' , '6.5.12'
    pod 'ProgressHUD' , '13.7.2'
    pod 'RealmSwift' , '10.42.1'
    pod 'CryptoSwift' , '1.8.0'

end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
        end
    end
end
